// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXzFlGdHdl6Ja2c64zc_yUITkMrtpWEwU',
    appId: '1:215827545585:android:74c661f9649c20cba85850',
    messagingSenderId: '215827545585',
    projectId: 'cultart-a4742',
    storageBucket: 'cultart-a4742.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD55nLHdPYbK3mBhxD8htyNpE-ywh2CnmY',
    appId: '1:215827545585:ios:81037f836e2c9b47a85850',
    messagingSenderId: '215827545585',
    projectId: 'cultart-a4742',
    storageBucket: 'cultart-a4742.appspot.com',
    androidClientId: '215827545585-5oaguv3t978on2duqfrdm304m1q980bk.apps.googleusercontent.com',
    iosClientId: '215827545585-hhs4umtu8qdgpo6sgoa3137j0isghguc.apps.googleusercontent.com',
    iosBundleId: 'com.example.cultart',
  );
}
